# -*- coding: utf-8 -*-
{
    'name': "Bouygues customization",
    'description':
    """
    Customization for Bouygues
    """,
    'category': '',
    'version': '15.0.0',
    'depends':
    [
        'base',
        'product',
        'sale',
        'stock',
        'sale_stock',
        'purchase',
        'purchase_product_matrix',
        'purchase_stock',
        'sale_management',
        'web',
        'sale_purchase',
        'purchase_requisition',
        'mrp',
        'mrp_subcontracting',
        'hr',
        'sales_team',
        'sale_product_matrix',
        'mail',
        'sale_renting',
        'uom',
        'stock_enterprise',
        'sale_mrp',
        'website',
        'website_sale',
        'website_sale_wishlist',
        'stock_account',
        'contacts',
        'auth_signup',
        'edi_base',
        'edi_ftp_connection',
        'edi_sftp_connection',
    ],
    'data': [
        # Data
        # 'data/fonctions.xml',
        # 'data/security_groups.xml',
        # 'data/sequence.xml',
        # 'data/mail_templates.xml',
        # 'data/stock_data.xml',
        # 'data/ir_cron.xml',
        # 'data/wms_export.xml',
        # 'data/wms_import.xml',

        # Security
        # 'security/ir.model.access.csv',
        # 'security/bouygues_security.xml',
        # 'security/ir_model_access.xml',

        # Reports
        # 'reports/paper_format.xml',
        # 'reports/delivery_slip.xml',
        # 'reports/purchase_order.xml',
        # 'reports/sale_order_report.xml',
        # 'reports/delivery_report.xml',
        # 'reports/subcontracting_delivery_report.xml',
        # 'reports/reception_report.xml',
        # 'reports/preparation_report.xml',
        # 'reports/manufacturing_report.xml',
        # 'reports/package_list_report.xml',
        # 'reports/return_report.xml',
        # 'reports/purchase_order_report.xml',
        # 'reports/sale_order_report_distrimo.xml',
        # 'reports/sale_report.xml',
        # 'reports/sale_report_dashboard.xml',
        # 'reports/purchase_report_dashboard.xml',
        # 'reports/stock_report_dashboard.xml',

        # Views
        # 'views/account_tax.xml',
        # 'views/product_template.xml',
        # 'views/product_category.xml',
        # 'views/product_public_category.xml',
        # 'views/product_product.xml',
        # 'views/purchase_order.xml',
        # 'views/sale_order.xml',
        # 'views/stock_move_line.xml',
        # 'views/stock_picking.xml',
        # 'views/stock_picking_type.xml',
        # 'views/package_type_type.xml',
        # 'views/product_supplierinfo.xml',
        # 'views/res_company.xml',
        # 'views/res_partner.xml',
        # 'views/res_users.xml',
        # 'views/exception_template.xml',
        # 'views/analytic_imputation.xml',
        # 'views/hr_employee.xml',
        # 'views/mrp_production.xml',
        # 'views/stock_move.xml',
        # 'views/type_type.xml',
        # 'views/stock_warehouse.xml',
        # 'views/website_sale_template.xml',
        # 'views/website_sale_portal.xml',
        # 'views/sale_portal_templates.xml',
        # 'views/assets.xml',
        # 'views/partner_category.xml',
        # 'views/stock_inventory.xml',
        # 'views/product_attribute.xml',
        # 'views/validation_template.xml',
        # 'views/purchase_family.xml',
        # 'views/ir_sequence.xml',
        # 'views/pablo_import.xml',
        # 'views/pablo_sale_order.xml',
        # 'views/stock_warehouse_orderpoint.xml',
        # 'views/res_config_settings_views.xml',
        # 'views/hr_employee_public.xml',
        # 'views/webclient_templates.xml',
        # 'views/website_sale_wishlist_template.xml',
        # 'views/export_wms.xml',
        # 'views/import_wms.xml',
        # 'views/stock_warning.xml',
        # 'views/sale_order_line.xml',
        # 'views/stock_picking_intersite.xml',
        # 'views/purchase_order_line.xml',
        # 'views/board_sale.xml',
        # 'views/board_purchase.xml',
        # 'views/board_stock.xml',
        # 'views/stock_location_route.xml',
        # 'views/variant_templates.xml',
        # 'views/portal_template.xml',

        # Wizard views
        # 'wizard/refused_reason.xml',
        # 'wizard/pablo_sale_order_warning.xml',
        # 'wizard/purchase_order_service_received.xml',
        # 'wizard/sale_order_service_delivered.xml',
        # 'wizard/sale_order_multiple_product.xml',
        # 'wizard/inventory_extraction_date.xml',
        # 'wizard/product_margin.xml',
        # 'wizard/sales_count_extraction.xml',
        # 'wizard/pr_analysis_extraction.xml',
        # 'wizard/product_rotation_rate.xml',
        # 'wizard/product_template_update_name.xml',
        # 'wizard/product_product_update_name.xml',
        # 'wizard/stock_picking_return.xml',
        # 'wizard/sale_order_line_edit_price.xml',
        # 'wizard/purchase_order_line_edit_price.xml',
        # 'wizard/rental_wizard.xml',

    ],
    'demo': [],
    'pre_init_hook': 'pre_init_hook',
    'qweb': [
    ],
    'auto_install': False,
}
