# -*- coding: utf-8 -*-
from . import account_tax
from . import analytic_imputation
from . import hr_employee_base
from . import ir_http
from . import ir_sequence
from . import mail_thread
from . import monkey_patch
from . import mrp_production
from . import pablo_import
from . import pablo_sale_order
from . import pablo_sale_order_line
from . import package_type
from . import package_type_type
from . import partner_category
from . import product_attribute_value
from . import product_category
from . import product_public_category
from . import product_location_responsible
from . import product_product
from . import product_supplierinfo
from . import product_template
from . import purchase_family
from . import purchase_order
from . import purchase_order_line
from . import res_company
from . import res_config_settings
from . import res_partner
from . import res_users
from . import res_zip
from . import sale_order
from . import sale_order_line
from . import set_values
from . import stock_move
from . import stock_move_line
from . import stock_picking
from . import stock_picking_type
from . import stock_quant
from . import stock_warehouse
from . import stock_warehouse_orderpoint
from . import type_type
from . import validation_delegation
from . import validation_template
from . import wms_export_edi
from . import wms_import_edi
from . import stock_warning
from . import stock_rule
from . import edi_synchronization
from . import base_model
from . import stock_picking_intersite
from . import stock_picking_intersite_line
from . import board_sale
from . import ir_ui_view_custom
from . import board_purchase
from . import board_stock
from . import stock_location_route
