from . import pablo_sale_order_warning
from . import portal_wizard
from . import portal_wizard_user
from . import refused_reason
from . import sale_make_invoice_advance
from . import sale_order_multiple_product
from . import purchase_order_service_received
from . import sale_order_service_delivered
from . import stock_picking_return
from . import inventory_extraction_date
from . import product_margin
from . import sales_count_extraction
from . import pr_analysis_extraction
from . import product_rotation_rate
from . import product_template_update_name
from . import product_product_update_name
from . import sale_order_line_edit_price
from . import purchase_order_line_edit_price
from . import rental_wizard
